apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "komodor-security-reporter.fullname" . }}
  labels:
    {{- include "komodor-security-reporter.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ include "komodor-security-reporter.configYaml" . | nindent 4 }}
